schemaVersion: 2.1.0
metadata:
  name: foreman-x509
  displayName: Foreman X509
projects:
  - name: foreman-x509
    git:
      remotes:
        origin: git@github.com:ludovicus3/foreman_x509.git
components:
  - name: tools
    container:
      endpoints:
        - name: foreman
          exposure: public
          protocol: http
          targetPort: 3000
      env:
        - name: RAILS_ENV
          value: development
        - name: FOREMAN_FQDN
          value: foreman.example.com
        - name: FOREMAN_DOMAIN
          value: example.com
        - name: DATABASE_URL
          value: postgresql://{{postgresUser}}:{{postgresPassword}}@localhost/{{postgresDb}}?pool=5
      image: 'quay.io/ludovicus/rails-developer-image:stream9'
      memoryLimit: 2G
      mountSources: true
  - name: postgresql
    container:
      endpoints:
        - exposure: none
          name: postgresql
          targetPort: 5432
      env:
        - name: POSTGRES_USER
          value: '{{postgresUser}}'
        - name: POSTGRES_PASSWORD
          value: '{{postgresPassword}}'
        - name: POSTGRES_DB
          value: '{{postgresDb}}'
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      image: ghcr.io/theforeman/postgresql-evr:13
      mountSources: false
      volumeMounts:
        - name: data
          path: /var/lib/postgresql/data
  - name: data
    volume:
      size: 10Gi
variables:
  postgresDb: foreman
  postgresUser: foreman
  postgresPassword: REDACTED